# Generated by Django 3.0.5 on 2020-07-04 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='userEmail',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
