# Generated by Django 3.0.5 on 2020-07-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200705_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='random',
        ),
    ]
