# Generated by Django 3.0.5 on 2020-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersnew',
            name='image',
            field=models.ImageField(blank=True, default='image/profile.jpg', null=True, upload_to='image/'),
        ),
    ]
